name: esds-blog
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - ablog
  - cftime
  - colorspacious
  - dask
  - dask-labextension
  - distributed
  - graphviz
  - ipywidgets
  - jupyterlab
  - matplotlib
  - myst-nb
  - netcdf4
  - pydata-sphinx-theme
  - python-graphviz
  - scipy
  - seaborn
  - sparse
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinxcontrib-bibtex
  - xarray
  - sphinxext-rediraffe
  - sphinx-design
  - sphinx-copybutton
  - sphinxext-opengraph
